### ISSUE TITLE
can be able to choose time from timep-icker component  without click on button

### ISSUE THREAD

**Issue by MEM94** [livelybone/vue-datepicker#13]
I'm working on project and I used livelybone/vue-datepicker , I have an issue (if end-user wants to pick time without need to click on button) , there any props I can use to fix it.

**Comment by livelybone** [comment]
which component are you using?

**Comment by ZoreAnkit** [comment]
@livelybone I would like to thank you for the package its very useful.  

I'm facing same issue as @MEM94 is. I'm using datatimepicker component. Is there a way to see time component without clicking on date may be have clock icon and when we click on it we can change time
![Selection_063](https://user-images.githubusercontent.com/46300882/161062100-c0ab7a9a-802c-40d8-844b-f8a36090ed14.png)

![Selection_065](https://user-images.githubusercontent.com/46300882/161063619-f740d7bc-3fd1-4c2c-93d1-d7f14c63b643.png)


some icon type of thing beside Ok button to select time instead of clicking on date.

**Comment by livelybone** [comment]
I am so busy these days that it's too late to rely. I'll think about the suggestion.
